# Background and foreground colors
background = #101913
foreground = #a1af9c

# Standard colors
palette = 0=#101913
palette = 1=#c87a5c
palette = 2=#6aae52
palette = 3=#c4a64e
palette = 4=#4a9a68
palette = 5=#8a7856
palette = 6=#52987a
palette = 7=#a1af9c

# Bright colors
palette = 8=#4a684a
palette = 9=#d89268
palette = 10=#82c45a
palette = 11=#d4ba60
palette = 12=#5aae7a
palette = 13=#a08e66
palette = 14=#48aa82
palette = 15=#b0c2a6
