background            #101913
foreground            #a1af9c

# black
color0  #101913
color8  #4a684a

# red
color1  #c87a5c
color9  #d89268

# green
color2  #6aae52
color10 #82c45a

# yellow
color3  #c4a64e
color11 #d4ba60

# blue
color4  #4a9a68
color12 #5aae7a

# magenta
color5  #8a7856
color13 #a08e66

#cyan
color6  #52987a
color14 #48aa82

#white
color7  #a1af9c
color15 #b0c2a6


